language: objective-c
osx_image: xcode9.2
xcode_sdk: iphonesimulator11.2

before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
- brew outdated xctool || brew upgrade xctool

script:
  - pod repo update && pod install
  - carthage update --platform iOS
  - xctool -workspace OnionBrowser2.xcworkspace -scheme OnionBrowser2 -sdk iphonesimulator11.2 -configuration Debug -destination platform='iOS Simulator',OS=11.2,name='iPhone 8' -launch-timeout 120 run-tests -testTimeout 120 -resetSimulator

notifications:
  email: false
